version: "3"
services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      TZ: "Europe/Istanbul"
      PORT: 8081
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASS: root
      MYSQL_DB: user
    ports:
      - "8081:8081"

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      TZ: "Europe/Istanbul"
      MYSQL_DATABASE: user
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
